### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by amontD** [badgerodon/penv#1]
HELP!    I want to add a environment  however it output:

failed to save environment: stat /Users/up_ding/.config/penv.sh: no such file or directory

**Comment by calebdoxsey** [comment]
Hi @yifengding,

I think I fixed the issue. Are you using OSX? It would fail if you didn't already have a `.config` folder in your home directory.

If you want to give it another try you can install the latest version with `-u`:

```
go get -u github.com/badgerodon/penv/...
```

**Comment by amontD** [comment]
thx @calebdoxsey  it works
